server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:h2:mem:ams;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: mysql
  flyway:
    user: user
    password: password
    url: jdbc:mysql://localhost:3306/ams?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false
